CREATE TABLE IF NOT EXISTS t_chatMessage (
	id INT(11) NOT NULL AUTO_INCREMENT,
	to_user_id INT(12) DEFAULT NULL,
	from_user_id INT(12) DEFAULT NULL,
	chat_message TEXT DEFAULT NULL,
	timestamp INT(12) DEFAULT NULL,
	created DATETIME DEFAULT NULL,
	createdBy VARCHAR(50) DEFAULT NULL,
	updated DATETIME DEFAULT NULL,
	updatedBy VARCHAR(50) DEFAULT NULL,
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;